### ISSUE TITLE
想问下，同样的主板，但是CPU是13900K，能否直接使用呢？

### ISSUE THREAD

**Issue by zhangjiemin000** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#1]

**Comment by xtvj** [comment]
revcpuname 改成 13th Intel Core i9-13900K
这个只是在关于本机时显示的名字，其实是可以随便写的。
机型iMacPro1,1时ProcessorType不用变，机型MacPro7,1时改为3842，这个好像跟机型有关，跟CPU无关。
如果不知道在哪改可以用OCAT工具右上角的搜索功能

其它步骤就是在Windows下定制自己机箱的UTBMap.kext
还有如果你想提高性能跑分之类的东西，可以加上CPUFriend.kext、CPUFriendDataProvider.kext驱动，可以找别人同是13900K的EFI里面的这两个文件，然后用[OCAT](https://github.com/ic005k/OCAuxiliaryTools)工具能很方便的加上去。

祝你顺利！

<img width="1462" alt="截屏2023-04-13 22 43 15" src="https://user-images.githubusercontent.com/11442821/231798445-9c742969-a713-45ca-a341-555774b05043.png">
