### ISSUE TITLE
请教 音频异常 + 6950xt 显卡读不到

### ISSUE THREAD

**Issue by LyonUp** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#3]
你好！首先感谢大佬的无私分享 我的配置是：同样的主板 + 13900kf + 6950xt。

13900kf 参考另一个 issue，加上了 CPUFriend.kext、CPUFriendDataProvider.kext 驱动。

系统已经装好了 但是播放视频没声音 + 显卡读不到（显示图形卡 5M），网上搜发现 6950xt 不能免驱动，需要伪装成 6900xt。

所以想问问 可以在系统已经安装好的情况下 搞定显卡音频驱动吗 还是需要重新装？

音频、显卡问题 具体该怎么解决呢？谢谢！期待您的回复

**Comment by xtvj** [comment]
https://github.com/nakquada/Z790-Hackintosh
参考这个人的EFI可以使用6950XT显卡，他的ACPI文件有对显卡做定制，我的ACPI是直接自动生成，没对显卡做修改的。

也可以直接用他的EFI，然后用OCAT升级到最新版本，然后有什么问题可以按我的REDME.md文件去改一些BUG（BUG不多的）

系统安装好了就不用重新安装了，只是动EFI文件的问题，大不了就是执行一次CleanNvram

音频问题就不知道是哪个问题了，我这EFI已经加上了音频ALC897的，具体没声音我也不确定哪出了问题。

我不是大佬，我也是抄的别人的EFI，看没几个人分享我就分享出来了，一点点改，在远景论坛看别人解决了问题，我就加上来而已，哈哈。。

**Comment by xtvj** [comment]
看了下他的EFI，应该是用ACPI文件夹下的SSDT-BRG0文件来对6950xt做处理，然后在DP下添加了6900xt的ID

<img width="1081" alt="截屏2023-06-06 21 39 00" src="https://github.com/xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh/assets/11442821/db00f577-9c15-460f-8806-e37829775f53">

**Comment by LyonUp** [comment]
音频ALC897 我带耳机有声音 外放hdmi没有。


> 看了下他的EFI，应该是用ACPI文件夹下的SSDT-BRG0文件来对6950xt做处理，然后在DP下添加了6900xt的ID
> 
> <img alt="截屏2023-06-06 21 39 00" width="1081" src="https://user-images.githubusercontent.com/11442821/243713886-db00f577-9c15-460f-8806-e37829775f53.png">

对 我参考他的设置了DP，但是没拷ACPI里的SSDT-BRRG0。导致名字确实变了 还是读不到，我现在拷SSDT试试。

音频我带耳机有声音，外放走的是hdmi 没有声音。

**Comment by LyonUp** [comment]
> 看了下他的EFI，应该是用ACPI文件夹下的SSDT-BRG0文件来对6950xt做处理，然后在DP下添加了6900xt的ID
> 
> <img alt="截屏2023-06-06 21 39 00" width="1081" src="https://user-images.githubusercontent.com/11442821/243713886-db00f577-9c15-460f-8806-e37829775f53.png">

按照这个方式解决了 感谢！显卡读到后 hdmi音频也可以了、连睡眠也好了。

**Comment by LyonUp** [comment]
> 看了下他的EFI，应该是用ACPI文件夹下的SSDT-BRG0文件来对6950xt做处理，然后在DP下添加了6900xt的ID
> 
> <img alt="截屏2023-06-06 21 39 00" width="1081" src="https://user-images.githubusercontent.com/11442821/243713886-db00f577-9c15-460f-8806-e37829775f53.png">

非常棒地解决了问题
