### ISSUE TITLE
求测试一下睡眠和bios里的智能超频功能

### ISSUE THREAD

**Issue by Pain-and-Love** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#4]

**Comment by xtvj** [comment]
测试了下睡眠不正常，只是屏幕关了，但网页视频还一直在播。
超频这东西的话可能要加CPUFriend的驱动，我不确定，并且我需求不高就一直没搞，有空我会适配下13700K的配置。
这两个问题我会慢慢找方法去搞，但很可能需要很长时间。发自己的EFI出来以为会有很多同主板的EFI被分享出来，然后我好COPY，结果一直没出现。。。

**Comment by xtvj** [comment]
<img width="400" alt="截屏2023-07-29 01 04 58" src="https://github.com/xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh/assets/11442821/8ad5c589-fc71-4c10-9593-bcbbc2a47cc4">

Bios里打6GHz的预设模式，可以睿频到6GHz，但是运行了三次跑分软件，只过了一次，还有一个直接死机了，大概率是我的散热不行。
EFI默认是可以将13700K睿频到5.4，再高的话只能通过改Bios设定来提高频率了，而且通过Bios来提高频率的话要有很好的散热设备。

**Comment by mingweiarthurli** [comment]
BIOS里的6GHz自动超频不是所有CPU都能跑上去的，得比较雕的才行……
休眠在我的机器上测试是正常的，需要给`boot-args`添加`npci=0x2000`，同时需要关闭BIOS里的resize bar来避免二次休眠后睡死的问题（代价有点大，看你有多在意休眠），唤醒时需要点击两次鼠标或键盘（这个无解）。

**Comment by jas0nxu** [comment]
同款主板，我可以正常休眠唤醒，而且我还解决了第二次唤醒会变成重启的问题。我喜欢全功能都开，resizebar开着，vt-d也开着，集显也开（windows下有可能用上），ErP也开着。
需要折腾，大概这样：
1. resizebar启用，集显开启预分配64M显存，apex size设置为1024M，这个很关键，如果你dump bios你会看到有个参数和它关联。这个解决了休眠唤醒问题
2. vt-d这个开会导致wifi卡没法用，这是由于ACPI DMAR有oem保留段所导致，我是自己按照国外论坛教程去掉保留段，ACPI patch进去。好像opencore 0.9.5还是0.9.3开始，有个disableIoMapperMapping可以达到这个效果

**Comment by jas0nxu** [comment]
对了，boot-args需要加上-wegnoigpu，macos里禁用集显

**Comment by xtvj** [comment]
> 对了，boot-args需要加上-wegnoigpu，macos里禁用集显

这个很有用，感谢分享

**Comment by mingweiarthurli** [comment]
> 同款主板，我可以正常休眠唤醒，而且我还解决了第二次唤醒会变成重启的问题。我喜欢全功能都开，resizebar开着，vt-d也开着，集显也开（windows下有可能用上），ErP也开着。 需要折腾，大概这样：
> 
> 1. resizebar启用，集显开启预分配64M显存，apex size设置为1024M，这个很关键，如果你dump bios你会看到有个参数和它关联。这个解决了休眠唤醒问题
> 2. vt-d这个开会导致wifi卡没法用，这是由于ACPI DMAR有oem保留段所导致，我是自己按照国外论坛教程去掉保留段，ACPI patch进去。好像opencore 0.9.5还是0.9.3开始，有个disableIoMapperMapping可以达到这个效果

感谢提供解决方案，我自己也根据这个试了下，BIOS版本F9：
- Resize BAR开启，aperture size设置为1024MB，集显预分配显存没有改，还是默认的60MB，可以正常休眠唤醒，也没有二次休眠后无法唤醒的问题。
- VT-d开启，-wegnoigpu已添加，OpenCore中同时开启disableIoMapper和disableIoMapperMapping两个quirk，Wi-Fi和以太网没有问题。仅开启后者还是会出现网卡不正常的问题。

**Comment by jas0nxu** [comment]
> > 同款主板，我可以正常休眠唤醒，而且我还解决了第二次唤醒会变成重启的问题。我喜欢全功能都开，resizebar开着，vt-d也开着，集显也开（windows下有可能用上），ErP也开着。 需要折腾，大概这样：
> > 
> > 1. resizebar启用，集显开启预分配64M显存，apex size设置为1024M，这个很关键，如果你dump bios你会看到有个参数和它关联。这个解决了休眠唤醒问题
> > 2. vt-d这个开会导致wifi卡没法用，这是由于ACPI DMAR有oem保留段所导致，我是自己按照国外论坛教程去掉保留段，ACPI patch进去。好像opencore 0.9.5还是0.9.3开始，有个disableIoMapperMapping可以达到这个效果
> 
> 感谢提供解决方案，我自己也根据这个试了下，BIOS版本F9：
> 
> * Resize BAR开启，aperture size设置为1024MB，集显预分配显存没有改，还是默认的60MB，可以正常休眠唤醒，也没有二次休眠后无法唤醒的问题。
> * VT-d开启，-wegnoigpu已添加，OpenCore中同时开启disableIoMapper和disableIoMapperMapping两个quirk，Wi-Fi和以太网没有问题。仅开启后者还是会出现网卡不正常的问题。

1. 嗯，第一个关键是那个aperture size大小要大于等于1024M。
2. VT-D那个我是自定义apci去掉oem段配合disableIoMapperMapping，翻了一下这个quirk是解决venture当时新版本pcie控制器驱动的逻辑，你提到的第一个disableIoMapper那个我倒不知道，感谢分享

**Comment by jas0nxu** [comment]
@mingweiarthurli 你有使用白果网卡吗？如果有的话那个usb线你有接在主板上的插针上吗？
我用bcm943602cs，usb如果插在主板上（它们是内部一个hub分出来的端口），休眠后立马唤醒（是darkwake，显示器不显示，敲键盘或鼠标再亮屏），如果我用转接线转插到主板后面的usb口（不管是内部hub还是这个后面usb口我都定制为internal）则休眠很正常。
我原来一直以为经过hub蓝牙休眠肯定有问题，直到元旦我装另外一台机器，12490F+微星迫击炮，那个主板上usb也是内部hub分出来的，但是只需要对那个hub设置为internal，居然休眠很正常。
我有点拿不准这个是bios差异还是我两张网卡型号不一样的差异，微星这张是bcm94360cs，自带一个BRCM hub，看到usb拓扑是usb hub->BRCM hub->蓝牙，技嘉上则是usb hub->蓝牙。

**Comment by mingweiarthurli** [comment]
> > > 同款主板，我可以正常休眠唤醒，而且我还解决了第二次唤醒会变成重启的问题。我喜欢全功能都开，resizebar开着，vt-d也开着，集显也开（windows下有可能用上），ErP也开着。 需要折腾，大概这样：
> > > 
> > > 1. resizebar启用，集显开启预分配64M显存，apex size设置为1024M，这个很关键，如果你dump bios你会看到有个参数和它关联。这个解决了休眠唤醒问题
> > > 2. vt-d这个开会导致wifi卡没法用，这是由于ACPI DMAR有oem保留段所导致，我是自己按照国外论坛教程去掉保留段，ACPI patch进去。好像opencore 0.9.5还是0.9.3开始，有个disableIoMapperMapping可以达到这个效果
> > 
> > 
> > 感谢提供解决方案，我自己也根据这个试了下，BIOS版本F9：
> > 
> > * Resize BAR开启，aperture size设置为1024MB，集显预分配显存没有改，还是默认的60MB，可以正常休眠唤醒，也没有二次休眠后无法唤醒的问题。
> > * VT-d开启，-wegnoigpu已添加，OpenCore中同时开启disableIoMapper和disableIoMapperMapping两个quirk，Wi-Fi和以太网没有问题。仅开启后者还是会出现网卡不正常的问题。
> 
>     1. 嗯，第一个关键是那个aperture size大小要大于等于1024M。
> 
>     2. VT-D那个我是自定义apci去掉oem段配合disableIoMapperMapping，翻了一下这个quirk是解决venture当时新版本pcie控制器驱动的逻辑，你提到的第一个disableIoMapper那个我倒不知道，感谢分享

启用disableIoMapper是来源于这个反馈：https://github.com/acidanthera/bugtracker/issues/2278#issuecomment-1540539551

> @mingweiarthurli 你有使用白果网卡吗？如果有的话那个usb线你有接在主板上的插针上吗？ 我用bcm943602cs，usb如果插在主板上（它们是内部一个hub分出来的端口），休眠后立马唤醒（是darkwake，显示器不显示，敲键盘或鼠标再亮屏），如果我用转接线转插到主板后面的usb口（不管是内部hub还是这个后面usb口我都定制为internal）则休眠很正常。 我原来一直以为经过hub蓝牙休眠肯定有问题，直到元旦我装另外一台机器，12490F+微星迫击炮，那个主板上usb也是内部hub分出来的，但是只需要对那个hub设置为internal，居然休眠很正常。 我有点拿不准这个是bios差异还是我两张网卡型号不一样的差异，微星这张是bcm94360cs，自带一个BRCM hub，看到usb拓扑是usb hub->BRCM hub->蓝牙，技嘉上则是usb hub->蓝牙。

我是使用白果网卡替换了原装的Intel网卡，型号是Fenvi的BCM94360NG，这是块M.2无线网卡，没有USB接线，蓝牙应该是直接走的M.2接口。我这边也有需要再次点击鼠标键盘才能唤醒显示器的问题，但是由于我看网上反映相同问题的人不少，我以为这是正常的。
由于我的UTBMap是几个月之前定制的，我不是很记得我当时是如何设定的。但是由于我在Windows系统下开启了Hyper-V，USBToolBox是看不到我主板的USB接口的，得在一个没有开启Hyper-V的系统下操作，所以具体我这边的拓扑是怎样的，得等我有时间了装个新系统或者WinToGo后再来看看。

**Comment by jas0nxu** [comment]
@mingweiarthurli 我没替换掉主板自带的，那个windows下速率很高。你那个二次输入唤醒，使用usbwakefixup.kext即可，配套的apci补丁里XDC需要改成XDCI

**Comment by Pain-and-Love** [comment]
> BIOS里的6GHz自动超频不是所有CPU都能跑上去的，得比较雕的才行…… 休眠在我的机器上测试是正常的，需要给`boot-args`添加`npci=0x2000`，同时需要关闭BIOS里的resize bar来避免二次休眠后睡死的问题（代价有点大，看你有多在意休眠），唤醒时需要点击两次鼠标或键盘（这个无解）。

为什么说关闭  resize bar 代价有点大？

**Comment by mingweiarthurli** [comment]
> > BIOS里的6GHz自动超频不是所有CPU都能跑上去的，得比较雕的才行…… 休眠在我的机器上测试是正常的，需要给`boot-args`添加`npci=0x2000`，同时需要关闭BIOS里的resize bar来避免二次休眠后睡死的问题（代价有点大，看你有多在意休眠），唤醒时需要点击两次鼠标或键盘（这个无解）。
> 
> 为什么说关闭 resize bar 代价有点大？

Resize BAR可以有效提高游戏帧数，如果你的机器是双系统，又会在Windows下打游戏的话，Resize BAR最好打开，上面的老哥已经分享了更完美的解决办法。
