### ISSUE TITLE
最高睿频正常吗?

### ISSUE THREAD

**Issue by Pain-and-Love** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#5]
我是 13900k， 理论最高睿频是 5.8
但是实际上只有 5.6

> BIOS里没有调整过超频相关的参数, 不确定是不是要手动调一下cpu超频

![4651BC85-F80F-44B4-A0C7-E046CCA1D690](https://github.com/xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh/assets/9690422/61d89f41-35a9-4716-ba1d-a5ca4a0b303e)

**Comment by xtvj** [comment]
我的也是，你这情况跟我一样，设置默认为自动，结果用这工具看了最高好像是5.3，我的是13700K。
之前手动生成的CPU驱动加上去没起作用，就没折腾了，前几天看到CPUfriend的工具更新了，我有时间试试能不能自动生成一个加上去吧

**Comment by Pain-and-Love** [comment]
https://github.com/stevezhengshiqi/one-key-cpufriend/blob/main/README_CN.md
我看远景上有个帖子说用这个可以解决

**Comment by xtvj** [comment]
你看下是不是Bios的自动睿频没设置成开启，应该是有自动、禁用、开启三个选项吧，不确定了。
我的13700K开始自动睿频，可以达到5.4GHz，Bios中开启6GHz的预设模式也能达到6GHz，但感觉系统不太稳定。

使用[CPUFriend](https://github.com/acidanthera/CPUFriend/releases/)可以生成CPUFriendDataProvider
下载包解压后在Tools文件中运行命令：
```
./ResourceConverter.sh --kext ./DSDT.aml
```
前提是把自己生成的DSDT文件也放在这个文件夹下。
附我自己原先生成的DSDT文件。
[DSDT.aml.zip](https://github.com/xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh/files/12197267/DSDT.aml.zip)
