### ISSUE TITLE
Stuck on [EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by Castled00r** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#6]
Thanks for the share! Did you create the efi following the dortania guide? If I follow dortania, im getting [EB|#LOG:EXITBS:START] error. But using your efi, the installee works!

**Comment by xtvj** [comment]
I made the EFI file according to dortania guide, and after finishing the EFI, I have undergone a lot of modifications. These modifications are all learned from other people's experience posts in [a hackintosh forum](https://bbs.pcbeta.com/forum-570-1.html).

**Comment by Castled00r** [comment]
Thanks! Did you do anything other then dortania for creating the efi or did the installer booted right away?

**Comment by xtvj** [comment]
It was several months ago. After I finished the EFI, it started smoothly, but the performance was not good. Later, I referred to another person's EFI and turned on or off several parameters. These months, I changed some problems such as Mac model, Bluetooth configuration, WIFI connection, etc., but I didn’t have much research on sleep and performance issues.
The problem of startup stuck is generally done according to the [official guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html), but I can't tell exactly what caused it.

**Comment by Castled00r** [comment]
Great! I used your efi as now most things are working great. Last question: did you use bluetooth and wifi native or did you have a dongle/pcie card?

**Comment by xtvj** [comment]
I use bluetooth and wifi native.
[AirportItlwm.kext](https://github.com/OpenIntelWireless/itlwm) is used to drive WiFi
[IntelBluetoothFirmware.kext and IntelBTPatcher.kext](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) are used to drive Bluetooth
