### ISSUE TITLE
bluetoothd进程的内存占用不断变高

### ISSUE THREAD

**Issue by miaoshengkun** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#7]
- 电脑配置
CPU: i9 13900KF
RAM: 32 GB 6000 MHz * 2
GPU: AMD 6800XT
OS Version: macOS Ventura (13.5.0)

主板同款，蓝牙设备只有妙控板连接，尚未定制USB驱动，另外板载Wi-Fi也无法使用

**Comment by xtvj** [comment]
关注了下，bluetoothd进程确实变高了，这个可能要跟[蓝牙驱动](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)或[官方](https://github.com/acidanthera/BrcmPatchRAM)反馈信息了，不确定是哪个出的问题。

板载WiFi我没用，一直使用的是有线，真不能用的话我想到的两个原因是：USB定制、WiFi驱动不是最新。
我的EFI里面USB定制有一点点瑕疵，但应该不影响WiFi，可以试下最新的[WiFi驱动](https://github.com/OpenIntelWireless/itlwm/releases)，尤其是开发版的，那个作者更新的挺快的。

**Comment by miaoshengkun** [comment]
无线不能使用的问题我怀疑是[BlueToolFixup](https://github.com/acidanthera/BrcmPatchRAM/releases)导致的，我把它禁用了就好了

**Comment by miaoshengkun** [comment]
另外我重新安装了macOS Sonoma(14.1.2)，把所有的插件都更新了，目前除了蓝牙无法使用，其他都正常

**Comment by xtvj** [comment]
我更新到14.2，蓝牙也正常使用，你是不是USB定制有问题，可能需要重新定制下USB。
