### ISSUE TITLE
请教~安装过程报错 start::512:Successfully initialized AHCI controller

### ISSUE THREAD

**Issue by checkycky** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#8]
报错页面和这个问题一样，start::512:Successfully initialized AHCI controller一段时间后出现禁止标志
https://www.tonymacx86.com/threads/opencore-stuck-at-start-512-successfully-initialized-ahci-controller.326433/

禁止标志页面是花屏的，依稀能看到左下角出现 still waiting for the root device

1. 不知道和我用的DRAM，GPU有关系吗？ 
DDR5-7200MHZ 
NVIDIA 40系（在configlist里把AMD的kext和引导删掉了，准备用核显驱动）

2. AHCI重做和免AHCI补丁都试过还是出错

请问应该如何修复这个问题？ 感谢！

**Comment by xtvj** [comment]
黑苹果不支持英伟达的显卡，40系的就更不可能支持了。
换个AMD的显卡吧。
11代CPU及更新的CPU核显也不支持。

**Comment by checkycky** [comment]
> 

谢谢，原来核显也不支持了 : )
