### ISSUE TITLE
wifi and bluetooth works?

### ISSUE THREAD

**Issue by abodypa9** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#9]
thanks, but wifi and bluetooth works??

**Comment by xtvj** [comment]
我在旅行，不太方便找资料，按之前的使用体验来讲，自行更新蓝牙和无线网络驱动到最新版，或是更新到开发版，一般是可以驱动成功的。

**Comment by xtvj** [comment]
我已经更新到MacOS14.2，蓝牙一直正常，但没测试过WiFi，应该是正常的。
